import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Car } from './src/models/Car.js';

dotenv.config();

const seedCars = async () => {
  try {
    await mongoose.connect(process.env.DATABASE_URL || 'mongodb://localhost:27017/topspeed');
    
    // Clear existing cars
    await Car.deleteMany({});
    
    const carsData = [
      { brand: 'Aston Martin', model: 'Vantage 2025', year: 2025, engine: { displacement: 5204, cylinders: 12, type: 'V12' }, horsepower: 725, torque: 753, fuelType: 'Petrol', acceleration: 3.4, topSpeed: 340, drivetrain: 'RWD', category: 'Sports', price: 199000, imageUrl: '/images/cars/aston-martin-vantage-2025.jpg', description: 'Aston Martin Vantage 2025 - Ultimate luxury sports car' },
      { brand: 'Audi', model: 'A8L 2025', year: 2025, engine: { displacement: 2995, cylinders: 6, type: 'Twin-turbo I-6' }, horsepower: 355, torque: 369, fuelType: 'Petrol', acceleration: 5.8, topSpeed: 250, drivetrain: 'AWD', category: 'Sedan', price: 82000, imageUrl: '/images/cars/audi-a8l-2025.jpg', description: 'Audi A8L - Flagship luxury sedan' },
      { brand: 'Audi', model: 'e-tron GT 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 630, torque: 928, fuelType: 'Electric', acceleration: 3.4, topSpeed: 260, drivetrain: 'AWD', category: 'Sports', price: 105000, imageUrl: '/images/cars/audi-e-tron-gt-2025.jpg', description: 'Audi e-tron GT - High-performance electric grand tourer' },
      { brand: 'Audi', model: 'Q8 2025', year: 2025, engine: { displacement: 2998, cylinders: 6, type: 'Twin-turbo I-6' }, horsepower: 345, torque: 369, fuelType: 'Petrol', acceleration: 5.5, topSpeed: 250, drivetrain: 'AWD', category: 'SUV', price: 72000, imageUrl: '/images/cars/audi-q8-2025.jpg', description: 'Audi Q8 - Premium performance SUV' },
      { brand: 'Audi', model: 'RS7', year: 2024, engine: { displacement: 3996, cylinders: 8, type: 'Turbocharged V8' }, horsepower: 661, torque: 626, fuelType: 'Petrol', acceleration: 3.3, topSpeed: 305, drivetrain: 'AWD', category: 'Sedan', price: 125000, imageUrl: '/images/cars/audi-rs7.jpg', description: 'Audi RS7 - High-performance wagon' },
      { brand: 'Bentley', model: 'Continental Speed', year: 2024, engine: { displacement: 5950, cylinders: 12, type: 'Twin-Turbocharged W12' }, horsepower: 667, torque: 738, fuelType: 'Petrol', acceleration: 3.5, topSpeed: 335, drivetrain: 'AWD', category: 'Coupe', price: 280000, imageUrl: '/images/cars/bentley-speed.jpg', description: 'Bentley Continental Speed - Ultimate British luxury' },
      { brand: 'BMW', model: 'i7 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 536, torque: 516, fuelType: 'Electric', acceleration: 4.6, topSpeed: 250, drivetrain: 'AWD', category: 'Sedan', price: 110000, imageUrl: '/images/cars/bmw-i7-2025.jpg', description: 'BMW i7 - Luxury electric sedan' },
      { brand: 'BMW', model: 'M4 Competition 2025', year: 2025, engine: { displacement: 2993, cylinders: 6, type: 'Twin-turbo I-6' }, horsepower: 625, torque: 750, fuelType: 'Petrol', acceleration: 3.8, topSpeed: 250, drivetrain: 'AWD', category: 'Sedan', price: 105000, imageUrl: '/images/cars/bmw-m4-competition-2025.jpg', description: 'BMW M4 Competition - Performance sedan' },
      { brand: 'BMW', model: 'M440i', year: 2024, engine: { displacement: 2998, cylinders: 6, type: 'Turbocharged Inline-6' }, horsepower: 503, torque: 479, fuelType: 'Petrol', acceleration: 4.2, topSpeed: 250, drivetrain: 'AWD', category: 'Sedan', price: 80000, imageUrl: '/images/cars/bmw-m440i.jpg', description: 'BMW M440i - Performance sedan' },
      { brand: 'BMW', model: 'X7 M60i 2025', year: 2025, engine: { displacement: 4395, cylinders: 8, type: 'Twin-turbo V8' }, horsepower: 523, torque: 553, fuelType: 'Petrol', acceleration: 4.8, topSpeed: 250, drivetrain: 'AWD', category: 'SUV', price: 105000, imageUrl: '/images/cars/bmw-x7-m60i-2025.jpg', description: 'BMW X7 M60i - Luxury SUV' },
      { brand: 'Bugatti', model: 'Bolide', year: 2024, engine: { displacement: 7993, cylinders: 16, type: 'Quad-Turbocharged W16' }, horsepower: 1600, torque: 1200, fuelType: 'Petrol', acceleration: 2.17, topSpeed: 500, drivetrain: 'AWD', category: 'Sports', price: 5000000, imageUrl: '/images/cars/bugatti-bolide.jpg', description: 'Bugatti Bolide - Fastest hypercar' },
      { brand: 'BYD', model: 'Seal 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Motor' }, horsepower: 190, torque: 310, fuelType: 'Electric', acceleration: 7.2, topSpeed: 180, drivetrain: 'FWD', category: 'Sedan', price: 35000, imageUrl: '/images/cars/byd-seal-2025.jpg', description: 'BYD Seal - Affordable electric sedan' },
      { brand: 'Cadillac', model: 'Escalade 2025', year: 2025, engine: { displacement: 5984, cylinders: 8, type: 'V8' }, horsepower: 420, torque: 460, fuelType: 'Petrol', acceleration: 5.9, topSpeed: 200, drivetrain: 'AWD', category: 'SUV', price: 80000, imageUrl: '/images/cars/cadillac-escalade-2025.jpg', description: 'Cadillac Escalade - Luxury SUV' },
      { brand: 'Chevrolet', model: 'Corvette Z06 2025', year: 2025, engine: { displacement: 5498, cylinders: 8, type: 'V8' }, horsepower: 670, torque: 630, fuelType: 'Petrol', acceleration: 2.6, topSpeed: 330, drivetrain: 'RWD', category: 'Sports', price: 105000, imageUrl: '/images/cars/chevrolet-corvette-z06-2025.jpg', description: 'Chevrolet Corvette Z06 - American supercar' },
      { brand: 'Chevrolet', model: 'Corvette E-Ray', year: 2024, engine: { displacement: 5498, cylinders: 8, type: 'Hybrid V8' }, horsepower: 655, torque: 667, fuelType: 'Hybrid', acceleration: 2.5, topSpeed: 330, drivetrain: 'AWD', category: 'Sports', price: 120000, imageUrl: '/images/cars/corvette-e-ray.jpg', description: 'Chevrolet Corvette E-Ray - Hybrid supercar' },
      { brand: 'Dodge', model: 'Challenger Hellcat 2025', year: 2025, engine: { displacement: 6200, cylinders: 8, type: 'Supercharged V8' }, horsepower: 645, torque: 719, fuelType: 'Petrol', acceleration: 3.6, topSpeed: 300, drivetrain: 'RWD', category: 'Coupe', price: 95000, imageUrl: '/images/cars/dodge-challenger-hellcat-2025.jpg', description: 'Dodge Challenger Hellcat - American muscle' },
      { brand: 'Dodge', model: 'Charger Daytona', year: 2024, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 670, torque: 740, fuelType: 'Electric', acceleration: 3.3, topSpeed: 300, drivetrain: 'AWD', category: 'Coupe', price: 95000, imageUrl: '/images/cars/dodge-charger-daytona.jpg', description: 'Dodge Charger Daytona - Electric muscle' },
      { brand: 'Ferrari', model: '296GTB 2025', year: 2025, engine: { displacement: 2993, cylinders: 6, type: 'Twin-turbo Hybrid V6' }, horsepower: 819, torque: 920, fuelType: 'Hybrid', acceleration: 2.9, topSpeed: 340, drivetrain: 'RWD', category: 'Sports', price: 380000, imageUrl: '/images/cars/ferrari-296gtb-2025.jpg', description: 'Ferrari 296GTB - Hybrid supercar' },
      { brand: 'Ferrari', model: '812 Superfast', year: 2024, engine: { displacement: 6496, cylinders: 12, type: 'Naturally Aspirated V12' }, horsepower: 789, torque: 718, fuelType: 'Petrol', acceleration: 2.9, topSpeed: 320, drivetrain: 'RWD', category: 'Sports', price: 450000, imageUrl: '/images/cars/ferrari-812.jpg', description: 'Ferrari 812 Superfast - V12 power' },
      { brand: 'Ferrari', model: 'SF90 2025', year: 2025, engine: { displacement: 3990, cylinders: 8, type: 'Twin-turbo V8 Hybrid' }, horsepower: 986, torque: 1050, fuelType: 'Hybrid', acceleration: 2.5, topSpeed: 340, drivetrain: 'AWD', category: 'Sports', price: 480000, imageUrl: '/images/cars/ferrari-sf90-2025.jpg', description: 'Ferrari SF90 - Hybrid flagship' },
      { brand: 'Genesis', model: 'G90 2025', year: 2025, engine: { displacement: 5000, cylinders: 8, type: 'Twin-turbo V8' }, horsepower: 425, torque: 516, fuelType: 'Petrol', acceleration: 5.0, topSpeed: 250, drivetrain: 'AWD', category: 'Sedan', price: 88000, imageUrl: '/images/cars/genesis-g90-2025.jpg', description: 'Genesis G90 - Luxury flagship' },
      { brand: 'Hyundai', model: 'Elantra 2025', year: 2025, engine: { displacement: 1599, cylinders: 4, type: 'Turbocharged I-4' }, horsepower: 195, torque: 195, fuelType: 'Petrol', acceleration: 7.5, topSpeed: 200, drivetrain: 'FWD', category: 'Sedan', price: 28000, imageUrl: '/images/cars/hyundai-elantra-2025.jpg', description: 'Hyundai Elantra - Affordable sedan' },
      { brand: 'Hyundai', model: 'Ioniq 5N 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 641, torque: 664, fuelType: 'Electric', acceleration: 3.4, topSpeed: 260, drivetrain: 'AWD', category: 'SUV', price: 65000, imageUrl: '/images/cars/hyundai-ioniq5n-2025.jpg', description: 'Hyundai Ioniq 5N - Performance electric SUV' },
      { brand: 'Hyundai', model: 'Tucson 2025', year: 2025, engine: { displacement: 2497, cylinders: 4, type: 'Turbocharged I-4' }, horsepower: 270, torque: 305, fuelType: 'Petrol', acceleration: 6.5, topSpeed: 210, drivetrain: 'AWD', category: 'SUV', price: 35000, imageUrl: '/images/cars/hyundai-tucson-2025.jpg', description: 'Hyundai Tucson - Family SUV' },
      { brand: 'Jaguar', model: 'F-Type 2025', year: 2025, engine: { displacement: 2997, cylinders: 6, type: 'Turbocharged Inline-6' }, horsepower: 575, torque: 531, fuelType: 'Petrol', acceleration: 3.5, topSpeed: 305, drivetrain: 'RWD', category: 'Sports', price: 105000, imageUrl: '/images/cars/jaguar-f-type-2025.jpg', description: 'Jaguar F-Type 2025 - Sports car' },
      { brand: 'Kia', model: 'EV9 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 516, torque: 516, fuelType: 'Electric', acceleration: 4.7, topSpeed: 250, drivetrain: 'AWD', category: 'SUV', price: 54000, imageUrl: '/images/cars/kia-ev9-2025.jpg', description: 'Kia EV9 - Electric luxury SUV' },
      { brand: 'Kia', model: 'Sportage 2025', year: 2025, engine: { displacement: 1999, cylinders: 4, type: 'Turbocharged I-4' }, horsepower: 227, torque: 258, fuelType: 'Petrol', acceleration: 7.0, topSpeed: 210, drivetrain: 'AWD', category: 'SUV', price: 32000, imageUrl: '/images/cars/kia-sportage-2025.jpg', description: 'Kia Sportage - Family SUV' },
      { brand: 'Lamborghini', model: 'Huracán Tecnica 2025', year: 2025, engine: { displacement: 5204, cylinders: 10, type: 'Naturally Aspirated V10' }, horsepower: 657, torque: 565, fuelType: 'Petrol', acceleration: 3.0, topSpeed: 370, drivetrain: 'RWD', category: 'Sports', price: 238000, imageUrl: '/images/cars/lamborghini-huracan-tecnica-2025.jpg', description: 'Lamborghini Huracán Tecnica - Final V10' },
      { brand: 'Lamborghini', model: 'Revuelto', year: 2024, engine: { displacement: 5996, cylinders: 12, type: 'Hybrid V12' }, horsepower: 1001, torque: 986, fuelType: 'Hybrid', acceleration: 2.5, topSpeed: 350, drivetrain: 'AWD', category: 'Sports', price: 550000, imageUrl: '/images/cars/lamborghini-revuelto.jpg', description: 'Lamborghini Revuelto - Hybrid flagship' },
      { brand: 'Lexus', model: 'LS500 2025', year: 2025, engine: { displacement: 3456, cylinders: 6, type: 'Twin-turbo I-6 Hybrid' }, horsepower: 413, torque: 442, fuelType: 'Hybrid', acceleration: 5.3, topSpeed: 250, drivetrain: 'AWD', category: 'Sedan', price: 75000, imageUrl: '/images/cars/lexus-ls500-2025.jpg', description: 'Lexus LS500 - Luxury hybrid sedan' },
      { brand: 'Lucid', model: 'Air Sapphire', year: 2024, engine: { displacement: 0, cylinders: 0, type: 'Electric Triple Motor' }, horsepower: 1234, torque: 1234, fuelType: 'Electric', acceleration: 1.89, topSpeed: 330, drivetrain: 'AWD', category: 'Sedan', price: 249000, imageUrl: '/images/cars/lucid-air-sapphire-2025.jpg', description: 'Lucid Air Sapphire - Electric performance' },
      { brand: 'McLaren', model: '750S 2025', year: 2025, engine: { displacement: 3994, cylinders: 8, type: 'Twin-turbo V8' }, horsepower: 740, torque: 800, fuelType: 'Petrol', acceleration: 2.8, topSpeed: 360, drivetrain: 'RWD', category: 'Sports', price: 308000, imageUrl: '/images/cars/mclaren-750s-2025.jpg', description: 'McLaren 750S - Performance supercar' },
      { brand: 'McLaren', model: 'Artura', year: 2024, engine: { displacement: 3994, cylinders: 8, type: 'Hybrid V8' }, horsepower: 680, torque: 720, fuelType: 'Hybrid', acceleration: 2.8, topSpeed: 330, drivetrain: 'RWD', category: 'Sports', price: 350000, imageUrl: '/images/cars/mclaren-artura.jpg', description: 'McLaren Artura - Hybrid supercar' },
      { brand: 'Mercedes-AMG', model: 'GT 63s 2025', year: 2025, engine: { displacement: 3982, cylinders: 8, type: 'Twin-turbo V8 Hybrid' }, horsepower: 630, torque: 664, fuelType: 'Hybrid', acceleration: 3.1, topSpeed: 315, drivetrain: 'AWD', category: 'Sports', price: 225000, imageUrl: '/images/cars/mercedes-amg-gt-63s-2025.jpg', description: 'Mercedes-AMG GT 63s - Hybrid sports' },
      { brand: 'Mercedes-Benz', model: 'C43 AMG', year: 2024, engine: { displacement: 1991, cylinders: 4, type: 'Turbocharged Hybrid I4' }, horsepower: 402, torque: 500, fuelType: 'Petrol', acceleration: 4.2, topSpeed: 280, drivetrain: 'AWD', category: 'Sedan', price: 85000, imageUrl: '/images/cars/mercedes-c43.jpg', description: 'Mercedes-Benz C43 AMG - Hybrid sedan' },
      { brand: 'Mercedes-Benz', model: 'EQS580 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 516, torque: 516, fuelType: 'Electric', acceleration: 4.6, topSpeed: 280, drivetrain: 'AWD', category: 'Sedan', price: 105000, imageUrl: '/images/cars/mercedes-eqs580-2025.jpg', description: 'Mercedes-Benz EQS580 - Luxury electric sedan' },
      { brand: 'Mercedes-Maybach', model: 'GLS600 2025', year: 2025, engine: { displacement: 5980, cylinders: 12, type: 'Twin-turbo V12' }, horsepower: 603, torque: 664, fuelType: 'Petrol', acceleration: 5.8, topSpeed: 250, drivetrain: 'AWD', category: 'SUV', price: 180000, imageUrl: '/images/cars/mercedes-maybach-gls600-2025.jpg', description: 'Mercedes-Maybach GLS600 - Luxury SUV' },
      { brand: 'Nissan', model: 'GT-R 2025', year: 2025, engine: { displacement: 3799, cylinders: 6, type: 'Twin-turbo V6' }, horsepower: 645, torque: 652, fuelType: 'Petrol', acceleration: 2.5, topSpeed: 330, drivetrain: 'AWD', category: 'Sports', price: 120000, imageUrl: '/images/cars/nissan-gtr-2025.jpg', description: 'Nissan GT-R 2025 - Performance legend' },
      { brand: 'Polestar', model: '4 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 516, torque: 516, fuelType: 'Electric', acceleration: 4.7, topSpeed: 260, drivetrain: 'AWD', category: 'SUV', price: 70000, imageUrl: '/images/cars/polestar-4-2025.jpg', description: 'Polestar 4 - Electric luxury SUV' },
      { brand: 'Porsche', model: '911 GT3 RS 2025', year: 2025, engine: { displacement: 3746, cylinders: 6, type: 'Naturally Aspirated Flat-6' }, horsepower: 518, torque: 388, fuelType: 'Petrol', acceleration: 3.2, topSpeed: 370, drivetrain: 'RWD', category: 'Sports', price: 225000, imageUrl: '/images/cars/porsche-911-gt3-rs-2025.jpg', description: 'Porsche 911 GT3 RS - Track machine' },
      { brand: 'Porsche', model: '911 Turbo S', year: 2024, engine: { displacement: 3746, cylinders: 6, type: 'Turbocharged Flat-6' }, horsepower: 640, torque: 590, fuelType: 'Petrol', acceleration: 2.6, topSpeed: 330, drivetrain: 'AWD', category: 'Sports', price: 210000, imageUrl: '/images/cars/porsche-911-turbo.jpg', description: 'Porsche 911 Turbo S - Performance icon' },
      { brand: 'Porsche', model: 'Cayenne Turbo 2025', year: 2025, engine: { displacement: 3996, cylinders: 8, type: 'Twin-turbo V8' }, horsepower: 670, torque: 738, fuelType: 'Petrol', acceleration: 3.8, topSpeed: 280, drivetrain: 'AWD', category: 'SUV', price: 165000, imageUrl: '/images/cars/porsche-cayenne-turbo-2025.jpg', description: 'Porsche Cayenne Turbo - Performance SUV' },
      { brand: 'Porsche', model: 'Taycan Turbo S 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 938, torque: 1093, fuelType: 'Electric', acceleration: 2.8, topSpeed: 300, drivetrain: 'AWD', category: 'Sedan', price: 165000, imageUrl: '/images/cars/porsche-taycan-turbo-s-2025.jpg', description: 'Porsche Taycan Turbo S - Electric sports' },
      { brand: 'Range Rover', model: 'Vogue 2025', year: 2025, engine: { displacement: 3996, cylinders: 6, type: 'Twin-turbo I-6' }, horsepower: 395, torque: 406, fuelType: 'Petrol', acceleration: 6.0, topSpeed: 240, drivetrain: 'AWD', category: 'SUV', price: 102000, imageUrl: '/images/cars/range-rover-vogue-2025.jpg', description: 'Range Rover Vogue - Luxury SUV' },
      { brand: 'Rivian', model: 'R1S 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Quad Motor' }, horsepower: 850, torque: 850, fuelType: 'Electric', acceleration: 3.0, topSpeed: 250, drivetrain: 'AWD', category: 'SUV', price: 80000, imageUrl: '/images/cars/rivian-r1s-2025.jpg', description: 'Rivian R1S - Electric adventure SUV' },
      { brand: 'Rolls-Royce', model: 'Cullinan 2025', year: 2025, engine: { displacement: 5980, cylinders: 12, type: 'Twin-turbo V12' }, horsepower: 563, torque: 627, fuelType: 'Petrol', acceleration: 5.2, topSpeed: 250, drivetrain: 'AWD', category: 'SUV', price: 330000, imageUrl: '/images/cars/rolls-royce-cullinan-2025.jpg', description: 'Rolls-Royce Cullinan - Luxury SUV' },
      { brand: 'Rolls-Royce', model: 'Ghost Black Badge', year: 2024, engine: { displacement: 5950, cylinders: 12, type: 'Twin-Turbocharged V12' }, horsepower: 593, torque: 664, fuelType: 'Petrol', acceleration: 4.6, topSpeed: 250, drivetrain: 'AWD', category: 'Sedan', price: 320000, imageUrl: '/images/cars/rolls-royce-ghost-bb.jpg', description: 'Rolls-Royce Ghost Black Badge - Luxury sedan' },
      { brand: 'Tesla', model: 'Model S 2024', year: 2024, engine: { displacement: 0, cylinders: 0, type: 'Electric Triple Motor' }, horsepower: 1080, torque: 1420, fuelType: 'Electric', acceleration: 1.89, topSpeed: 330, drivetrain: 'AWD', category: 'Sedan', price: 115000, imageUrl: '/images/cars/tesla-model-s-2024.jpg', description: 'Tesla Model S - Performance sedan' },
      { brand: 'Tesla', model: 'Model X Plaid 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Triple Motor' }, horsepower: 1020, torque: 1420, fuelType: 'Electric', acceleration: 2.5, topSpeed: 330, drivetrain: 'AWD', category: 'SUV', price: 105000, imageUrl: '/images/cars/tesla-model-x-plaid-2025.jpg', description: 'Tesla Model X Plaid - Electric SUV' },
      { brand: 'Tesla', model: 'Model 3 Highland 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 367, torque: 389, fuelType: 'Electric', acceleration: 5.2, topSpeed: 225, drivetrain: 'AWD', category: 'Sedan', price: 48000, imageUrl: '/images/cars/tesla-model3-highland-2025.jpg', description: 'Tesla Model 3 Highland - Affordable EV' },
      { brand: 'Toyota', model: 'Corolla 2025', year: 2025, engine: { displacement: 1798, cylinders: 4, type: 'I-4' }, horsepower: 169, torque: 163, fuelType: 'Petrol', acceleration: 9.2, topSpeed: 200, drivetrain: 'FWD', category: 'Sedan', price: 28000, imageUrl: '/images/cars/toyota-corolla-2025.jpg', description: 'Toyota Corolla - Reliable sedan' },
      { brand: 'Toyota', model: 'GR Supra 2025', year: 2025, engine: { displacement: 2998, cylinders: 6, type: 'Twin-turbo I-6' }, horsepower: 382, torque: 500, fuelType: 'Petrol', acceleration: 3.9, topSpeed: 250, drivetrain: 'RWD', category: 'Sports', price: 65000, imageUrl: '/images/cars/toyota-gr-supra-2025.jpg', description: 'Toyota GR Supra - Lightweight sports' },
      { brand: 'Toyota', model: 'Yaris 2025', year: 2025, engine: { displacement: 1490, cylinders: 3, type: 'I-3' }, horsepower: 120, torque: 123, fuelType: 'Petrol', acceleration: 11.0, topSpeed: 190, drivetrain: 'FWD', category: 'Hatchback', price: 20000, imageUrl: '/images/cars/toyota-yaris-2025.jpg', description: 'Toyota Yaris - City car' },
      { brand: 'Volvo', model: 'EX90 2025', year: 2025, engine: { displacement: 0, cylinders: 0, type: 'Electric Dual Motor' }, horsepower: 516, torque: 516, fuelType: 'Electric', acceleration: 4.9, topSpeed: 260, drivetrain: 'AWD', category: 'SUV', price: 85000, imageUrl: '/images/cars/volvo-ex90-2025.jpg', description: 'Volvo EX90 - Electric luxury SUV' },
    ];
    
    const result = await Car.insertMany(carsData);
    console.log(` ${result.length} cars added to database`);
    
    await mongoose.disconnect();
    console.log(' Database seeding complete!');
  } catch (error) {
    console.error(' Error seeding database:', error);
    process.exit(1);
  }
};

seedCars();
