import mongoose from 'mongoose';
import dotenv from 'dotenv';
import { Car } from './src/models/Car.js';

dotenv.config();

const seedCars = async () => {
  try {
    await mongoose.connect(process.env.DATABASE_URL || 'mongodb://localhost:27017/topspeed');
    
    // Clear existing cars
    await Car.deleteMany({});
    
    const carsData = [
      {
        brand: 'BMW',
        model: '335i',
        year: 2023,
        engine: {
          displacement: 2979,
          cylinders: 6,
          type: 'Turbocharged Inline-6',
        },
        horsepower: 382,
        torque: 369,
        fuelType: 'Petrol',
        acceleration: 4.8,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 65000,
        imageUrl: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800',
        description: 'High-performance luxury sedan with turbocharged engine',
        isVisible: true,
      },
      {
        brand: 'Mercedes-Benz',
        model: 'AMG C63',
        year: 2023,
        engine: {
          displacement: 3982,
          cylinders: 8,
          type: 'Turbocharged V8',
        },
        horsepower: 503,
        torque: 516,
        fuelType: 'Petrol',
        acceleration: 3.9,
        topSpeed: 290,
        drivetrain: 'RWD',
        category: 'Sedan',
        price: 75000,
        imageUrl: 'https://images.unsplash.com/photo-1553882900-d174edf69280?w=800',
        description: 'Powerful German performance car',
        isVisible: true,
      },
      {
        brand: 'Audi',
        model: 'RS6',
        year: 2023,
        engine: {
          displacement: 3996,
          cylinders: 10,
          type: 'Turbocharged V10',
        },
        horsepower: 591,
        torque: 590,
        fuelType: 'Petrol',
        acceleration: 3.6,
        topSpeed: 305,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 110000,
        imageUrl: 'https://images.unsplash.com/photo-1567818735868-e71b99932e29?w=800',
        description: 'Ultra-high performance station wagon',
        isVisible: true,
      },
      {
        brand: 'Porsche',
        model: '911 Carrera',
        year: 2023,
        engine: {
          displacement: 2981,
          cylinders: 6,
          type: 'Turbocharged Flat-6',
        },
        horsepower: 385,
        torque: 331,
        fuelType: 'Petrol',
        acceleration: 4.7,
        topSpeed: 308,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 125000,
        imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
        description: 'Iconic sports car with legendary handling',
        isVisible: true,
      },
      {
        brand: 'Lamborghini',
        model: 'Huracán',
        year: 2023,
        engine: {
          displacement: 5204,
          cylinders: 10,
          type: 'Naturally Aspirated V10',
        },
        horsepower: 631,
        torque: 443,
        fuelType: 'Petrol',
        acceleration: 2.9,
        topSpeed: 325,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 261000,
        imageUrl: 'https://images.unsplash.com/photo-1545587348-3e0a39a15d31?w=800',
        description: 'Exotic supercar with stunning performance',
        isVisible: true,
      },
      {
        brand: 'Ferrari',
        model: '296 GTB 2025',
        year: 2025,
        engine: {
          displacement: 2992,
          cylinders: 6,
          type: 'Twin-turbo V6 Hybrid',
        },
        horsepower: 660,
        torque: 565,
        fuelType: 'Hybrid',
        acceleration: 3.1,
        topSpeed: 330,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 420000,
        imageUrl: 'https://images.unsplash.com/photo-1592335808435-c6665a8324ce?w=800',
        description: 'Ferrari 296 GTB - Twin-turbo V6 masterpiece',
        isVisible: true,
      },
      {
        brand: 'Ferrari',
        model: 'SF90 Stradale 2025',
        year: 2025,
        engine: {
          displacement: 3990,
          cylinders: 8,
          type: 'Twin-turbo V8 Hybrid',
        },
        horsepower: 1000,
        torque: 900,
        fuelType: 'Hybrid',
        acceleration: 2.5,
        topSpeed: 340,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 500000,
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
        description: 'Ferrari SF90 Stradale - First hybrid V8 Ferrari',
        isVisible: true,
      },
      {
        brand: 'Ferrari',
        model: '812 Sport',
        year: 2025,
        engine: {
          displacement: 6262,
          cylinders: 12,
          type: 'Naturally Aspirated V12',
        },
        horsepower: 819,
        torque: 718,
        fuelType: 'Petrol',
        acceleration: 2.8,
        topSpeed: 320,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 380000,
        imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
        description: 'Ferrari 812 Sport - Ultimate V12 performance',
        isVisible: true,
      },
      {
        brand: 'Lamborghini',
        model: 'Revuelto 2025',
        year: 2025,
        engine: {
          displacement: 6498,
          cylinders: 12,
          type: 'Twin-turbo V12 Hybrid',
        },
        horsepower: 1001,
        torque: 986,
        fuelType: 'Hybrid',
        acceleration: 2.5,
        topSpeed: 350,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 575000,
        imageUrl: 'https://images.unsplash.com/photo-1542282088-fe8426682b8f?w=800',
        description: 'Lamborghini Revuelto - Hybrid flagship flagship',
        isVisible: true,
      },
      {
        brand: 'Lamborghini',
        model: 'Huracán Tecnica 2025',
        year: 2025,
        engine: {
          displacement: 5204,
          cylinders: 10,
          type: 'Naturally Aspirated V10',
        },
        horsepower: 640,
        torque: 565,
        fuelType: 'Petrol',
        acceleration: 2.99,
        topSpeed: 325,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 330000,
        imageUrl: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800',
        description: 'Lamborghini Huracán Tecnica - Track-focused V10',
        isVisible: true,
      },
      {
        brand: 'McLaren',
        model: '750S 2025',
        year: 2025,
        engine: {
          displacement: 3994,
          cylinders: 8,
          type: 'Twin-turbo V8',
        },
        horsepower: 750,
        torque: 800,
        fuelType: 'Petrol',
        acceleration: 2.8,
        topSpeed: 330,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 310000,
        imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
        description: 'McLaren 750S - Next-gen supercar',
        isVisible: true,
      },
      {
        brand: 'Porsche',
        model: '911 Turbo S 2025',
        year: 2025,
        engine: {
          displacement: 3745,
          cylinders: 6,
          type: 'Twin-turbo Flat-6',
        },
        horsepower: 640,
        torque: 820,
        fuelType: 'Petrol',
        acceleration: 2.7,
        topSpeed: 330,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 240000,
        imageUrl: 'https://images.unsplash.com/photo-1611339555312-e607c04352fa?w=800',
        description: 'Porsche 911 Turbo S - Ultimate icon reimagined',
        isVisible: true,
      },
      {
        brand: 'Porsche',
        model: '911 GT3 RS 2025',
        year: 2025,
        engine: {
          displacement: 3996,
          cylinders: 6,
          type: 'Naturally Aspirated Flat-6',
        },
        horsepower: 740,
        torque: 770,
        fuelType: 'Petrol',
        acceleration: 3.2,
        topSpeed: 340,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 220000,
        imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
        description: 'Porsche 911 GT3 RS - Track-focused precision',
        isVisible: true,
      },
      {
        brand: 'Chevrolet',
        model: 'Corvette Z06 2025',
        year: 2025,
        engine: {
          displacement: 5500,
          cylinders: 8,
          type: 'Naturally Aspirated V8',
        },
        horsepower: 670,
        torque: 610,
        fuelType: 'Petrol',
        acceleration: 2.6,
        topSpeed: 330,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 105000,
        imageUrl: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800',
        description: 'Chevrolet Corvette Z06 - American supercar',
        isVisible: true,
      },
      {
        brand: 'Nissan',
        model: 'GT-R 2025',
        year: 2025,
        engine: {
          displacement: 3799,
          cylinders: 6,
          type: 'Twin-turbo V6',
        },
        horsepower: 645,
        torque: 652,
        fuelType: 'Petrol',
        acceleration: 2.5,
        topSpeed: 330,
        drivetrain: 'AWD',
        category: 'Sports',
        price: 120000,
        imageUrl: 'https://images.unsplash.com/photo-1545587348-3e0a39a15d31?w=800',
        description: 'Nissan GT-R - Japanese performance legend',
        isVisible: true,
      },
      {
        brand: 'Toyota',
        model: 'GR Supra 2025',
        year: 2025,
        engine: {
          displacement: 2998,
          cylinders: 6,
          type: 'Twin-turbo I-6',
        },
        horsepower: 382,
        torque: 500,
        fuelType: 'Petrol',
        acceleration: 3.9,
        topSpeed: 250,
        drivetrain: 'RWD',
        category: 'Sports',
        price: 65000,
        imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
        description: 'Toyota GR Supra - Lightweight sports coupe',
        isVisible: true,
      },
      {
        brand: 'BMW',
        model: 'M4 Competition 2025',
        year: 2025,
        engine: {
          displacement: 2993,
          cylinders: 6,
          type: 'Twin-turbo I-6',
        },
        horsepower: 625,
        torque: 750,
        fuelType: 'Petrol',
        acceleration: 3.8,
        topSpeed: 250,
        drivetrain: 'AWD',
        category: 'Sedan',
        price: 105000,
        imageUrl: 'https://images.unsplash.com/photo-1552820728-8ac41f1ce891?w=800',
        description: 'BMW M4 Competition - Twin-turbo performance sedan',
        isVisible: true,
      },
    ];
    
    const result = await Car.insertMany(carsData);
    console.log(`✅ ${result.length} cars added to database`);
    
    await mongoose.disconnect();
    console.log('✅ Database seeding complete!');
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedCars();
